"""remove reference to group+leeson from attendance table

Revision ID: 04279a1bc110
Revises: 6bc088cde4f5
Create Date: 2026-05-04 10:03:51.226506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04279a1bc110'
down_revision: Union[str, None] = '6bc088cde4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
