"""add lessons table

Revision ID: 5ac077bda3a8
Revises: 49db932424b1
Create Date: 2026-05-04 07:10:15.702936

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5ac077bda3a8"
down_revision: Union[str, None] = "49db932424b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Изменяем существующую таблицу lessons
    op.drop_constraint("uq_lesson", "lessons", type_="unique")
    op.drop_constraint("lessons_group_id_fkey", "lessons", type_="foreignkey")
    op.drop_column("lessons", "group_id")
    op.drop_column("lessons", "date")
    op.drop_column("lessons", "lesson_type")
    op.drop_column("lessons", "teacher_name")
    op.add_column("lessons", sa.Column("kind", sa.String(length=20), nullable=False, server_default="lecture"))
    op.add_column("lessons", sa.Column("day", sa.Integer(), nullable=False, server_default="1"))
    op.add_column("lessons", sa.Column("week", sa.Integer(), nullable=False, server_default="1"))
    op.add_column("lessons", sa.Column("place", sa.String(length=200), nullable=True))
    op.alter_column("lessons", "room", existing_type=sa.String(length=100), type_=sa.String(length=500))
    op.alter_column("lessons", "kind", server_default=None)
    op.alter_column("lessons", "day", server_default=None)
    op.alter_column("lessons", "week", server_default=None)
    op.create_table(
        "teacher_lessons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("teacher_id", sa.Integer(), nullable=False),
        sa.Column("groups", sa.ARRAY(sa.Integer()), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["lessons.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["teacher_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "group_lessons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("teacher_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["id"], ["lessons.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["teacher_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "student_profiles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("telegram", sa.String(length=100), nullable=True),
        sa.Column("vk", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.drop_table("student_profile")
    op.drop_table("attendance_reports")
    op.drop_table("schedules")
    op.drop_index("ix_announcements_id", table_name="announcements")
    op.drop_index("ix_attachments_id", table_name="attachments")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_attachments_id", "attachments", ["id"], unique=False)
    op.create_index("ix_announcements_id", "announcements", ["id"], unique=False)
    op.create_table(
        "schedules",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('schedules_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("time", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("subject", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("place", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("building", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("room_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("sync", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("group_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("day", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("week", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.CheckConstraint("day >= 1 AND day <= 7", name="check_day_range"),
        sa.CheckConstraint("week >= 1 AND week <= 2", name="check_week_range"),
        sa.PrimaryKeyConstraint("id", name="schedules_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "attendance_reports",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("starosta_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("teacher_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("group_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "subject", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "lesson_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "present_student_ids",
            postgresql.ARRAY(sa.INTEGER()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("total_students", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("present_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name="attendance_reports_group_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["starosta_id"], ["users.id"], name="attendance_reports_starosta_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"], ["users.id"], name="attendance_reports_teacher_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="attendance_reports_pkey"),
    )
    op.create_table(
        "student_profile",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("group_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("phone", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column(
            "telegram", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column("vk", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name="student_profile_group_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="student_profile_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="student_profile_pkey"),
        sa.UniqueConstraint("user_id", name="student_profile_user_id_key"),
    )
    op.drop_table("student_profiles")
    op.drop_table("group_lessons")
    op.drop_table("teacher_lessons")
    # Откатываем изменения lessons
    op.drop_column("lessons", "place")
    op.drop_column("lessons", "kind")
    op.drop_column("lessons", "day")
    op.drop_column("lessons", "week")
    op.alter_column("lessons", "room", existing_type=sa.String(length=500), type_=sa.String(length=100))
    op.add_column("lessons", sa.Column("group_id", sa.Integer(), nullable=True))
    op.add_column("lessons", sa.Column("date", sa.Date(), nullable=True))
    op.add_column("lessons", sa.Column("lesson_type", sa.String(length=100), nullable=True))
    op.add_column("lessons", sa.Column("teacher_name", sa.String(length=255), nullable=True))
    op.create_foreign_key("lessons_group_id_fkey", "lessons", "groups", ["group_id"], ["id"], ondelete="CASCADE")
    op.create_unique_constraint("uq_lesson", "lessons", ["group_id", "date", "time_start", "subject"])
    # ### end Alembic commands ###
