"""fixes of events table

Revision ID: 9961d9b64b9f
Revises: 8abb1987aa66
Create Date: 2026-05-11 08:52:25.965314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9961d9b64b9f'
down_revision: Union[str, None] = '8abb1987aa66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
