"""remove reference to grouplesson and replase with Lesson

Revision ID: ec69e432924a
Revises: 04279a1bc110
Create Date: 2026-05-04 10:05:34.470294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec69e432924a'
down_revision: Union[str, None] = '04279a1bc110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
